### ISSUE TITLE
Gitlab CI Support

### ISSUE THREAD

**Issue by atomfrede** [pascalgrimaud/generator-jhipster-ci#1]
Hi Pascal,

do you plan to add gitlab-ci yaml file too? I thinks its a little complicated as the configuration depends highly on the used runner, but I think it would be cool to support gitlab ci too.

**Comment by pascalgrimaud** [comment]
Hello Frederik !

Yes I plan to do it, I don't forget your mail in dev mailing list.
As I never use Gitlab, I have to learn it before, with Docker of course ! :whale: 

Unless you know exactly how doing it, PR is welcome :sunglasses:
