### ISSUE TITLE
When test with Continuos Integration with gradle, use no-daemon

### ISSUE THREAD

**Issue by phouverneyuff** [pascalgrimaud/generator-jhipster-ci#11]
In the gradle documentation, they recommend use option --no-daemon when running in continuos integration server.

https://docs.gradle.org/current/userguide/gradle_daemon.html

> Continuous integration
> 
> At the moment, we recommend that you leave the Daemon disabled for continuous integration servers as using a fresh runtime for each build is more reliable since the runtime is completely isolated from previously builds. Additionally, since the Daemon primarily acts to reduce build startup times, this isn't as critical in CI as it is on a developer's machine.

**Comment by pascalgrimaud** [comment]
Oh, maybe we should do this for the main generator-jhipster too ?
https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/04-tests.sh

**Comment by phouverneyuff** [comment]
Yes.
