### ISSUE TITLE
Feature Request: Add BitBucket Pipelines Support

### ISSUE THREAD

**Issue by myspivey** [pascalgrimaud/generator-jhipster-ci#13]
As found here. https://confluence.atlassian.com/bitbucket/yaml-configuration-file-792298910.html

**Comment by pascalgrimaud** [comment]
thanks @myspivey 
I don't have much time, I have to update all my modules and add more support.
I will try to do it asap :)

**Comment by laszlomiklosik** [comment]
Hi @myspivey and @pascalgrimaud,

you might want to use the Docker image I just created (basically I combined the atlassian base image with the jhipster one).

Image: https://hub.docker.com/r/bluefloyd/jhipster-bitbucket-pipeline
Source: https://github.com/laszlomiklosik/jhipster-bitbucket-pipeline

Cheers,
Laszlo

**Comment by pascalgrimaud** [comment]
Really interesting.
But for the next weeks, I wont have time to work on it. I'm trying to work on the PR Kubernetes with Minikube and it takes me too much time!

Don't hesitate if you want to contribute!!

**Comment by pascalgrimaud** [comment]
I'm closing this, for the following reasons:
- I didn't have time to work on this
- I'm not a bitbucket user
- and now, this module is included directly to the main generator

So don't hesitate to open a new ticket to https://github.com/jhipster/generator-jhipster if you want to contribute by adding the bitbucket pipeline!
