### ISSUE TITLE
Change gitlab ci image/config

### ISSUE THREAD

**Issue by atomfrede** [pascalgrimaud/generator-jhipster-ci#14]
Gitlab not supports caching of artifacts, so I don't think we need the heavyweight image by @moifort anymore, as it is hard to maintain. You can make maven and gradle download there dependencies to a the correct location such that they are automatically cached by gitlab ci and cache node modules in addition. So all dependencies are downloaded once (the first run) only. 

So @moifort @pascalgrimaud whats your oppinion on this? My image can be found here: https://github.com/atomfrede/gitlab-ci-jhipster-stack

**Comment by pascalgrimaud** [comment]
LGTM !
I need to find time to work and update this module. PR is welcome too!

**Comment by atomfrede** [comment]
Maybe I was wrong, at least for the public shared runners provided by gitlab. Downloaded artifacts are cached:

```
Creating cache maven-test/master...
WARNING: node_modules: no matching files           
src/main/webapp/bower_components: found 2674 matching files 
cache: found 4398 matching files 
```

But each build downloads dependencies again. Using a specific runner works fine, don't know how it is supposed to work with their public runners.

**Comment by atomfrede** [comment]
@pascalgrimaud Good news! Using public, shared runners now works with caches, so we only need an image with java and node installed, will update the config soon.

**Comment by pascalgrimaud** [comment]
Nice ! So it's a very simple image

**Comment by atomfrede** [comment]
Exactly: https://github.com/atomfrede/gitlab-ci-jhipster-stack/blob/master/Dockerfile

**Comment by pascalgrimaud** [comment]
I tested your last PR and everything is OK for me. Thanks so much
I'm closing this and will release soon
