### ISSUE TITLE
Gitlab Ci with shared public runners

### ISSUE THREAD

**Issue by atomfrede** [pascalgrimaud/generator-jhipster-ci#4]
Currently the gitlab ci config seems not to work with public shared runners. As shared runners are enabled by default for public projects we should support it. 

I have setup a sample [project on gitlab](https://gitlab.com/atomfrede/jhipster-gitlab-ci).

@moifort already suggested to setup a dedicated docker image that contains all required tools for building and testing a jhipster app. Maybe we can link external services like pql into the build process which is [supported by gitlab ci](http://doc.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service) or usage the existing docker compose features.

**Comment by moifort** [comment]
I have the same problem. Sadly it's a random network problem (below), some time the server it's working sometime not. Happily the PR #5 will resolve this problem because the image contains the node_modules dependencies.

Can you explain more about using gitlab `services` because the way that I understand is more if you want to use a BDD or something, no? 

``` bash
Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
```

**Comment by moifort** [comment]
@atomfrede can you give me the access to your gitlab repo, so I can test?

**Comment by atomfrede** [comment]
Of course. Whats your username?

Regarding the services in gitlab ci, I only thought to keep the custom image small and just link the external services that are required by the current configuration (but you're image doesn't contain external services everything is fine).

**Comment by pascalgrimaud** [comment]
Builds are pending... https://gitlab.com/pascalgrimaud/hello-jhipster/builds
So long !

**Comment by moifort** [comment]
There are a problem, normally you need to have a least one running. I will check your config!

**Comment by moifort** [comment]
@atomfrede moifort_
@pascalgrimaud can you add me too moifort_

**Comment by pascalgrimaud** [comment]
@moifort : done! you are master, feel free to do what u want :)

**Comment by moifort** [comment]
Thank you!

**Comment by moifort** [comment]
You think it's possible to have access to your admin area? Because I don't have access to this menu :(

![capture d ecran 2015-12-28 a 22 47 31](https://cloud.githubusercontent.com/assets/4958079/12026028/17b63094-adb5-11e5-88db-2c11a396ac90.png)

**Comment by pascalgrimaud** [comment]
it's an open gitlab, exactly same as github, so I'm not admin (or root) => I don't see this option

**Comment by moifort** [comment]
I am sorry I don't know why it didn't work :(. I try to add my private runner but he doesn't want to add it. @atomfrede How you do with your configuration? you have your own runner?

**Comment by pascalgrimaud** [comment]
Oh don't worry @moifort we'll find the solution :+1:

**Comment by moifort** [comment]
:sob:

**Comment by pascalgrimaud** [comment]
I will restart the build and let them pending all night long :new_moon_with_face: => time to go to bed ;)

**Comment by moifort** [comment]
You are right, maybe it's the time to pull the image, because I have the same behavior with atomefred repo.

**Comment by atomfrede** [comment]
My private runners are still using the shell executor. I can update one runner with docker, but the Pc is at home (and switched off)  and I'm still on vacation until 4th of January

**Comment by pascalgrimaud** [comment]
@atomfrede : don't worry, happy holidays !!
@moifort : the build has finished with SUCCESS 4 hours ago. So your image works well. Long time to wait => https://gitlab.com/pascalgrimaud/hello-jhipster/builds?scope=finished

**Comment by atomfrede** [comment]
I'll setup an ubuntu vm and add this as private runner (maybe today). I've started a build with public shared runner infrastructure and will wait what happens.

**Comment by moifort** [comment]
Yes this morning I configurate a specific runner on my server. And the config it's totally different to mine. But need to improve because the maven cache is not used. And I need to create an specific image who works with open gitlab.

Envoyé de mon iPhone

**Comment by atomfrede** [comment]
There seems something wrong with shared runners. My build is pending for 12 hours now. My specific runners picks up the build immediately.

**Comment by pascalgrimaud** [comment]
Hard to work on this, if the shared runners are broken.

I have a question : is the `.gitlab.yml` file the same for shared runners and specific/personnal runners ?
If no => we can add a specific question to choose between shared runners and specific runners
If yes => we have to wait

**Comment by atomfrede** [comment]
As far as I know there is no difference. A shared runner is just a specific runner marked as shared (only admins of the gitlab instance can setup them). 

I have found some older issues with same problem (not picked up at all or after a long time). I think I will open an issue at the gitlab tracker.

**Comment by atomfrede** [comment]
For reference I've opened a support ticket on the [gitlab.com tracker](https://gitlab.com/gitlab-com/support-forum/issues/463).

**Comment by pascalgrimaud** [comment]
Thanks @atomfrede

**Comment by atomfrede** [comment]
Some news. We are not the only ones having issues with shared runners. But my build jobs have been picked up after qw hours or so. Let's see what the gitlab.com support says.

**Comment by pascalgrimaud** [comment]
So the PR from @moifort works well, as I expected. It's a good news!
The issue is only from shared runners

**Comment by atomfrede** [comment]
I guess everyone has seen the answer. Their public runners are not capable of handling that much builds at the moment, so I'll close this issue, as the gitlab ci integration works quite well.
